DROP TABLE IF EXISTS Trx;
CREATE TABLE Trx(
id INT PRIMARY KEY NULL,
ip VARCHAR(50)  NULL,
action VARCHAR(50)  NULL,
date DATE(50) NULL
);

CREATE SEQUENCE HIBERNATE_SEQUENCE
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1;
